#!/usr/bin/env bash

if [ -z "$(ls -A nizzetup-core)" ]; then
    curl -Lo nizzetup-core.zip https://github.com/edenvin/nizzetup-core/archive/master.zip
    unzip -j nizzetup-core.zip -d nizzetup-core
fi

nizzetup-core/run "$@"
