#! /usr/bin/env bash

configs=()

for config in configs/*; do
	configs+=($(basename "$config"))
done

function run_option {
	printf "\nExecuting $1\n"
	configs/$1
}

function show_menu {
	NR_OF_OPTIONS="${#configs[@]}"

	printf "\n"
	for i in $(seq 1 $NR_OF_OPTIONS); do
		printf "%i) %s\n" $i ${configs[$i - 1]}
	done
	printf "q) Quit\n\n" $(($NR_OF_OPTIONS + 1))

	read -p "Choose what to run: " ANSWER

	if [ $ANSWER = "q" ]; then
		exit 0
	elif [ $ANSWER -le $NR_OF_OPTIONS ]; then
		run_option "${configs[$ANSWER - 1]}"
	else
		printf "Invalid option\n\n"
	fi
}

# If we don't got any parameter we will do this interactively
if [ $# -eq 0 ]; then
	while [ 1 ]; do
		show_menu
	done
else
	for option in $@; do
		run_option $option
	done
fi
