#!/usr/bin/env bash

if ! command -v brew > /dev/null; then
    # Install Homebrew
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    
fi

# Load Homebrew into the current shell to be able to use it directly
eval "$(/opt/homebrew/bin/brew shellenv)"

# Turn off telemetrics
brew analytics off
