#! /usr/bin/env bash

read -p "Enter desired name of the machine: " display_name
read -p "Enter desired system name of the machine: " system_name

sudo scutil --set ComputerName $display_name
sudo scutil --set HostName $system_name
sudo scutil --set LocalHostName $system_name
sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string $mac_os_name


printf "Installing Xcode command line dev tools\n"
xcode-select --install
read -p "Complete the setup in the installation window and press enter" xcode_completed
